name: icosatabolne
publish_to: 'none'
description: Vib3code Abalone-inspired board game visualizer.
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  vib3_flutter:
    git:
      url: https://github.com/Domusgpt/vib3codeSDKv3.0.0.git
      ref: claude/project-review-planning-NWnhW
      path: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
